config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "splash#index"
  
  resources :groups do
    resources :investments
  end

  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :manage, Group, user_id: user.id
    can :manage, Investment, user_id: user.id

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_and_belongs_to_many :investment

  validates :name, presence: true, length: { in: 2..25 }
  validates :icon, presence: true
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user

  has_and_belongs_to_many :group

  validates :name, :amount, presence: true, length: { in: 2..25 }
  validates :amount, numericality: { only_float: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :investments, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, length: { in: 2..25 }

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # WALLETS

  def index
    @groups = current_user.groups.order(id: :desc)
    @amount = Investment.where(user_id: current_user.id).sum(:amount)
    @group = Group.first # Fix for missing group_id at the Navbar conditionals
  end

  def new
    @new_group = current_user.groups.new
    @icons = ['⚽', '🎮', '🚗', '🚢', '🚌', '🚊', '💈', '🏥', '🏭', '🏖️', '🍽️', '🥂', '🤖']
    @group = Group.first # Fix for missing group_id at the Navbar conditionals
  end

  def create
    @group = current_user.groups.new(group_params)
    @icons = ['⚽', '🎮', '🚗', '🚢', '🚌', '🚊', '💈', '🏥', '🏭', '🏖️', '🍽️', '🥂', '🤖']

    respond_to do |format|
      if @group.save
        flash[:success] = '...created!'
        format.html { redirect_to groups_path, notice: 'Wallet Created' }
      else
        flash[:error] = '...hmmm, try again'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @investments = Group.find(params[:group_id]).investment.order(id: :asc)
  end

  def new
    @group = Group.find(params[:group_id])
    @investment = current_user.investments.new
  end

  def create
    @investment = current_user.investments.new(investment_params)
    Group.find(params[:group_id]).investment.push(@investment)

    respond_to do |format|
      if @investment.save
        flash[:success] = '...created!'
        format.html { redirect_to group_investments_path, notice: 'Investment Created' }
      else
        flash[:error] = '...hmmm, try again'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def investment_params
    params.require(:investment).permit(:name, :amount, :user_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @new_group) do |form| %>
  <div class="icon-wrapper">
    <div class= "icon-container">
      <div class="field-new"><%= form.select :icon, @icons.map { |i| [i.to_s, i.to_s] }, {} %></div>
      <div class="field pad-new"><%= form.text_field :name, placeholder: "Name", required: true %></div>
    </div>


    <div>
      <%= form.submit "Save", class: 'save' %>
    </div>
  </div>
<%end%>

app/views/groups/_group.html.erb
<% unless current_page?(group_investments_path(group.id))%>
  <%= link_to group_investments_path(group.id) do %>
    <div class="icon-wrapper">
      
      <div class= "icon-container">
        <div class="icon">
          <%= group.icon %>
        </div>
        <div class="flex-vertical margin-left">
          <h4><%= group.name %><h4>
          <p><%= group.created_at.strftime("%d %B %Y") %></p>
        </div>
      </div>
      
      <div class="money-field">
        <h4>$<%= group.investment.sum(:amount) %></h4>
      </div>

    </div>
  <%end%>
<%else%>
  <div class="icon-wrapper">
  <div class="icon-container">
      <div class="icon">
        <%= group.icon %>
      </div>

      <div class="flex-vertical margin-left-bio">
        <h4><%= group.name %><h4>
        <div class="lorem">
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/groups/index.html.erb
<div>
  <div class="flex-horizontal wallet-total">
    <h4>Total</h4>
    <h4>$<%= @amount %></h4>
  </div>

  <div class="top-cards">
    <%= render @groups %>
  </div>

  <div class='footer-cards top-cards'>
    <%= button_to "New Wallet", new_group_path, method: :get, data: {turbo: false}, :class => "login green-button" %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render "form" %>

app/views/investments/_form.html.erb
<%= form_with(model: @investment, url: group_investments_path, method: :post) do |form| %>
  <div class="icon-wrapper">
    <div class= "icon-container">
      <div class="field pad-new"><%= form.text_field :name, placeholder: "Name", required: true %></div>
      <div class="field-new"><%= form.number_field :amount, step: :any, placeholder: "0.0", required: true %></div>
    <div>
      <%= form.submit "Save", class: 'save' %>
    </div>
  </div>
<%end%>

app/views/investments/_investment.html.erb
<div class="icon-wrapper">
    <h3>Transaction Nº00<%= rand(200...500)%><%= investment.id %></h3>
    <p><%= investment.name %>: <%= investment.created_at.strftime("%d %b %y at %l:%M %p")%></p>
</div>

app/views/investments/index.html.erb
<%= render 'groups/group', group: @group %>

<div class="top-cards">
  
  <%= render @investments %>

  <div>
    <div class= "icon-wrapper">
      <h4>TOTAL INVESTMENT</h4>
      <div class="money-field">
        <h4>$<%= @group.investment.sum(:amount) %></h4>
      </div>
    </div>
  </div>

</div>

<div class='footer-cards top-cards'>
    <%= button_to "New Investment", new_group_investment_path(@group.id), method: :get, data: {turbo: false}, :class => "login green-button" %>
  </div>

app/views/investments/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless current_page?(root_path) %>
      <div class="nav-bar">

        <% unless (current_page?(groups_path) || current_page?(new_user_registration_path) || current_page?(new_user_session_path) || current_page?(new_user_session_path) || current_page?(new_user_password_path)) || current_page?(edit_user_password_path) %>
          <button type="submit", class="save">
            <%= link_to '<', groups_path, data:{turbo:false} %>
          </button>
        <% end %>

        <% if current_page?(new_user_registration_path) %>
          <button type="submit", class="save">
            <%= link_to '<', root_path, data:{turbo:false} %>
          </button>
          <h2>SIGN UP</h2>
          <div></div>
          
        <% elsif current_page?(new_user_session_path) %>
          <button type="submit", class="save">
            <%= link_to '<', root_path, data:{turbo:false} %>
          </button>
          <h2>LOG IN</h2>
          <div></div>

        <% elsif current_page?(edit_user_password_path) %>
          <button type="submit", class="save">
            <%= link_to '<', root_path, data:{turbo:false} %>
          </button>
          <h2>EDIT PASSWORD</h2>
          <div></div>

        <% elsif current_page?(new_user_password_path) %>
          <button type="submit", class="save">
            <%= link_to '<', new_user_session_path, data:{turbo:false} %>
          </button>
          <h2>RESET PASSWORD</h2>
          <div></div>

          <% elsif current_page?(new_group_investment_path(@group.id)) %>
        <% end %>
        
        <% if user_signed_in? %>
          <% if current_page?(groups_path) %>
            <%= image_tag("menu.png", :alt => "menu button", :class => 'menu')%>
            <h2>WALLET</h2>
          <% elsif current_page?(new_group_path)%>
            <h2>NEW WALLET</h2>
          <% elsif current_page?(group_investments_path(@group.id)) %>
            <h2>INVESTMENTS</h2>
          <% end %>
        <% end %>

        <% if user_signed_in? %>
          <%= button_to "Sign out", destroy_user_session_path, :method => :delete, data:{turbo:false}, class: 'save' %>
        <% end %>
      </div>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<%= link_to groups_path do %>
  <h1>MY WALLET</h1>
<%end%>


<div class="position-bot">
  <div class="login"><%= link_to "LOG IN", new_user_session_path%><br /></div>
  <div class="signup"><%= link_to "SIGN UP", new_user_registration_path%><br /></div>
</div>